# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 07:53
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='content'),
        ),
    ]
